#!/bin/bash
#./Configure PC-PGI -DEST=${PWD}/dest> Makefile
#touch *.F
cp -f Makefile dest
cd dest
make histogram.x
if [ $? -ne 0 ] ; then
   exit
fi
make neci.a
if [ $? -ne 0 ] ; then
   exit
fi
cd ..
if [ -e "../cpmd.x" ]
then
   WD=$PWD
   cd ..
   make
   cd $WD
fi
