#!/bin/bash

usage() {
    cat<<END
usage: ./compile [-d] [platform]
Clean build of NECI using platform (default: PC-PGI64) as the configuration.
Options:
    -d Compile with the compiler debug options on.
END
}

dbgflag=''

while getopts 'dh' options; do
    case $options in
        d)  dbgflag='-d';;
        h)  usage
            exit 1;;
        \?) usage
            exit 1;;
        *)  usage
            exit 1;;
    esac
done

# Remove flags from argument list
shift $(($OPTIND - 1))

if [ "$#" -ne 0 ]; then
	platform=$1
elif [ -e .compileconf ]; then
	# Read the user's default platform (if the .compileconf exists 
	# in the current working directory).
	platform=`cat .compileconf`
else
	platform=PC-PGI64
fi
echo "Using platform: $platform"

./mkconfig.sh $dbgflag $platform -DEST=${PWD}/DESTDIR > mktemplate

cp irat.inc dest
cp irat.inc kdest
sed -e 's/#CMPLXFLAG//' -e "s/DESTDIR/dest/" mktemplate > dest/Makefile
sed -e 's/#CMPLXFLAG/-D__CMPLX/' -e "s/DESTDIR/kdest/"  mktemplate > kdest/Makefile

touch *.F *.F90
make clean
cd dest
make neci.x
stat=$?
cd ..
exit $stat
