#!/bin/bash
#./mkconfig.sh PC-PGI64 -DEST=${PWD}/dest> Makefile
#touch *.F
#cp -f Makefile dest
cd dest
make neci.x
if [ $? -ne 0 ] ; then
   exit
fi
#make neci.a
#if [ $? -ne 0 ] ; then
#   exit
#fi
#cd ..
#if [ -e "../cpmd.F" ]
#then
#   WD=$PWD
#   cd ..
#   make
#   cd $WD
#fi
