#!/bin/bash
# Initialise modules for compiling code via cron, and then call the compile
# script.

usage() {
    cat<<END
usage: ./croncompile [-ld] [platform]
Clean build of NECI using platform (default: PC-PGI64) as the configuration.  Prints out module information and can load required modules if needed.  
Options:
    -d Compile with the compiler debug options on.
    -l Load modules (assuming platform is recognised).
END
}

load=0
dbgflag=''
while getopts 'dlh' options; do
    case $options in
        d) dbgflag='-d';;
        h) usage
           exit 1;;
        l) load=1;;
        \?) usage
            exit 1;;
        *)  usage
            exit 1;;
    esac
done

# Remove flags from argument list
shift $(($OPTIND - 1))

. /usr/share/modules/init/bash
module purge

echo $dbflag
platform=$1
echo "Requested platform: $platform"

if [[ $load -eq 1 ]]; then
    case $platform in
        PC-PGI) module load pgi/32/7.0/7;;
        PC-PGI64) module load pgi/64/7.0/7;;
        PC-ifort64) module load ifort/64/10.1/015 acml/64/ifort/4.0/up;;
        *) echo "Default: use PC-PGI64"
           platform=PC-PGI64
           module load pgi/64/7.0/7;;
    esac
fi

echo "Loaded modules:"
module list
echo "Using platform: "$platform

./compile $dbgflag $platform
