#!/bin/bash
# Initialise modules for compiling code via cron, and then call the compile
# script.

. /usr/share/modules/init/bash
module purge

platform=$1

case $platform in
	PC-PGI) module load pgi/32/7.0/7;;
	PC-PGI64) module load pgi/64/7.0/7;;
	*) echo "Default: use PC-PGI64"
	   platform=PC-PGI64
	   module load pgi/64/7.0/7;;
esac

./compile $platform
