C     ==================================================================
C     == Used in parallel version otherwise GEQ0 is always .TRUE.     ==
C     == GEQ0 = .TRUE. if the processors are the 0 component          ==
C     ==================================================================
      LOGICAL       GEQ0
      COMMON/GEQ0L/ GEQ0
C     ==================================================================
