#define LogAlloc(ERR,NAME,LEN,SIZE,TAG) CALL LogMemAlloc(NAME,LEN,SIZE,this_routine,TAG)
#define LogDealloc(TAG) CALL LogMemDealloc(this_routine,TAG)
#define IsNullDet(nI) (nI(1).eq.0)
#define IsOcc(ilut,orb) btest(ilut((orb-1)/32), mod(orb-1,32))
#define IsNotOcc(ilut,orb) (.not.IsOcc(ilut,orb))
