!  necimain is the entry point for a standalone NECI.  It reads in an input, and then runs the NECI Core
Program NECI
!  Purely for some trunk compatibility
!       USE System , only : NEL,TSPN,LMS,TPARITY,IPARITY,NMAXX,NMAXY,    &
!     &  NMAXZ,NMSH,BOX,BOA,COA,TALPHA,ALPHA,ISTATE,TUEG,THUB,UHUB,BHUB, &
!     &  TTILT,ITILTX,ITILTY,TREADINT,TPBC,TREAL,THFORDER,TCSF,STOT,     &
!     &  FUEGRS,TCPMD,TDFREAD,FRC,TBIN
!      USE Calc , only : NEVAL,B2L,NCYCLE,NBLK,NKRY,TRHOOFR,TREAD,       &
!     &  TCORR,TFODM,IOBS,JOBS,KOBS,TENERGY,TMC,NHISTBOXES,BETA,I_P,     &
!     &  TRHOIJ,RHOEPSILON,TREADRHO,NPATHS,TMONTE,IMCSTEPS,IEQSTEPS,     &
!     &  TTROT,I_HMAX,TCALCHMAT,NWHTAY,I_VMAX,TBEGRAPH,TNPDERIV,BETAP,   &
!     &  BETAEQ,TMCDET,MDK,DETINV,TBLOCK,NDETWORK,TSPECDET,SPECDET,      &
!     &  DBETA,ICILEVEL
!      USE Integrals , only : NTAY,THFBASIS,THFCALC,NHFIT,HFMIX,HFEDELTA,&
!     &  ORBORDER,NFROZEN,NTFROZEN,TRHF,HFCDELTA,IHFMETHOD,TREADHF,      &
!     &  TREADTUMAT
!      USE Logging , only : ILOGGING
    Implicit none
    Write(6,*) "STARTING NECI"
!  ios will tell us if there's been an error reading in
! Pass in iCacheFlag as 0
    Call NECICore(0,.False.) !Indicate not called by CPMD
!  Horror oh horror.  trunk compability
!      if (ios.eq.0)                                                     &
!     & CALL NECICB(NEL,TSPN,LMS,TPARITY,IPARITY,NMAXX,NMAXY,NMAXZ,      &
!     &	NMSH,BOX,BOA,COA,TALPHA,ALPHA,ISTATE,NEVAL,B2L,NCYCLE,NBLK,     &
!     &	NKRY,TRHOOFR,TREAD,TCORR,TFODM,IOBS,JOBS,KOBS,TENERGY,TMC,      &
!     &	NHISTBOXES,BETA,I_P,TRHOIJ,RHOEPSILON,TREADRHO,NPATHS,TMONTE,   &
!     &  IMCSTEPS,IEQSTEPS,TTROT,I_HMAX,TCALCHMAT,NTAY,NWHTAY,I_VMAX,    &
!     &  ILOGGING,TUEG,TBEGRAPH,THFBASIS,THUB,UHUB,BHUB,TNPDERIV,        &
!     & BETAP,BETAEQ,TMCDET,MDK,DETINV,THFCALC,NHFIT,TTILT,ITILTX,ITILTY,&
!     & TBLOCK,HFMIX,HFEDELTA,TREADINT,TPBC,TREAL,NDETWORK,ORBORDER,     &
!     &   NFROZEN,NTFROZEN,TRHF,HFCDELTA,IHFMETHOD,TREADHF,TSPECDET,     &
!     &   SPECDET,DBETA,TREADTUMAT,THFORDER,TCSF,STOT,ICILEVEL,FUEGRS,   &
!     &   TCPMD,TDFREAD,fRc,0,TBIN)


End Program NECI
