#!/bin/bash

if [ $# -ne 3 ]; then
    cat <<END
$0: Calculate subspace eigenvalues for an eigenvalue problem specified by a
mean overlap and Hamiltonian matrix. It will create files which have the
same form as lowdin.* files output by NECI in KP-FCIQMC calculations.

This script calls the executable created from compiling lowdin_analysis.f90,
which is found in the tools subdirectory of NECI. This program performs the
averaging and the solution to the eigenvalue problem.

This script should be run in the directory containing hamil.* files, which are
generated by running KP-FCIQMC calculations in NECI. It will automatically
find all hamil.* files and perform averaging and orthogonalisation for all
these cases.

Exactly three arguments were not supplied.

Usage:

$0 path nrows nrepeats

where path is the location of the executable, nrows is the number of rows in
each matrix estimate, and nrepeats is the number of repeats for both the
overlap and Hamiltonian matrix.
END
    exit 1
fi

for file in hamil.*; do
    "${1}/lowdin.x" $2 $3 "hamil.${file##*.}" "overlap.${file##*.}" > "av.${file##*.}"
done
