#!/bin/bash

RC=0
SBIN=0

ROOT_DIR=$PWD

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# checkout changed files
for FILE in $(git diff-index --cached --name-only HEAD); do
    git checkout-index --prefix=$TMPDIR/ $FILE 2> /dev/null
done

cd $TMPDIR

if [ -x $ROOT_DIR/tools/check_style.py ]; then
    if ! $ROOT_DIR/tools/check_style.py ./; then
        RC=1
    fi
fi

exit $RC
