# Acquire the TCHINT package

# Provides:
# TCHINT_NECI_FOUND
# TCHINT_NECI_INCLUDE_PATHS
# TCHINT_NECI_LIBRARIES
# TCHINT_NECI_DEFINITIONS

find_package( TCHINT REQUIRED)
set( TCHINT_NECI_FOUND ${TCHINT_FOUND})
set( TCHINT_NECI_LIBRARIES tchint)  
set( TCHINT_NECI_DEFINITIONS USE_TCHINT_)

